GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "Novo Evento",
  "description": "Um novo evento",
  "date": "2024-06-01T00:00:00",
  "price": 100
}

###
@eventId = {{ createEvent.response.body.id }}


###
GET http://localhost:3000/events/{{eventId}}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "Novo Evento 2",
  "description": "Um novo evento",
  "date": "2024-06-01T00:00:00",
  "price": 100
}

###
DELETE http://localhost:3000/events/{{eventId}}

### Spots
GET http://localhost:3000/events/{{ eventId }}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{ eventId }}/spots
Content-Type:  application/json

{
  "name": "A4"
}

###
@spotId = {{ createSpot.response.body.id }}

###
@spotName = {{ createSpot.response.body.name }}


###
GET http://localhost:3000/events/{{ eventId }}/spots/{{spotId}}

###
PATCH http://localhost:3000/events/{{ eventId }}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "A1"
}

###
DELETE http://localhost:3000/events/{{ eventId }}/spots/{{spotId}}
